<a href="https://colab.research.google.com/github/falin23333/falin23333/blob/main/Clase_08_numpy_idbootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<div style="text-align: left"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBPtuRucr_9WOZ-DOIie_vrhYHmihX_mvQOw&usqp=CAU" width="600" /></div>

**Docentes:** Verónica Barraza y Diego Frigerio 
![orange-divider](https://user-images.githubusercontent.com/7065401/98619088-44ab6000-22e1-11eb-8f6d-5532e68ab274.png) 


# Introducción a Numpy

Vamos a conocer la primer libería externa a Python nativo que nos va a estar acompañando a lo largo del curso

Empezaremos a dar nuestros primeros pasos con NumPy. Es muy importante que googlees y consultes la documentación. Si no la instalaste, ahora es un buen momento.

Cuando queremos usar una librería, primero debemos importarla. Más adelante veremos qué significa importar una librería, pero podemos entenderlo como que es un aviso a Python de que vamos a incorporar nuevas funcionalidades; en este caso, desde NumPy.

In [ ]:
import numpy as np

## El array como estructura de datos

* Extenderemos la aplicación de estos tipos de estructura de datos, agregando el tipo de dato array. 
* Tanto array como list sirven para guardar conjuntos de datos ordenados en memoria. 
* Mientras que el tipo de dato list puede guardar datos de diferentes tipos, el tipo de dato array guarda datos de un único tipo. 
* Esto le permite ser más eficiente, especialmente al trabajar con conjuntos de datos grandes. 

## Numpy arrays

* La librería Numpy provee una forma particular de array llamada ndarray o Numpy Array.
* Recordar: los ndarrays, al ser un tipo de array, sólo pueden almacenar datos de un mismo tipo.

Ahora nuestro ambiente de trabajo sabe que si ponemos algo del estilo np. significa que esa funcionalidad la debe buscar en NumPy. Importante: Si la librería NO se instaló correctamente, te saltará un mensaje de error.

El principal tipo de dato sobre el que trabaja NumPy son los arreglos o arrays. Los arreglos son parecidos a listas y, de hecho, se pueden crear a partir de ellas.

In [ ]:
import numpy as np
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero son más que una lista. Algunas cosas que no se podían hacer con las listas ahora sí se pueden con arreglos. Recordemos que sumarle un número a toda la lista no estaba permitido

In [ ]:
lista + 1

TypeError: ignored

Como lo hacíamos?

In [ ]:
print(arreglo)

[0 1 2 3 4 5]


¡Pero ahora con los arreglos sí!

In [ ]:
print(arreglo * 10)

[ 0 10 20 30 40 50]


Esto simplifica mucho hacer cuéntas. Pero no es sólo sumar, también muchas otras operaciones:

In [ ]:
print(arreglo - 5)
print(arreglo - 2)
print(arreglo*4)
print(arreglo**2)

[-5 -4 -3 -2 -1  0]
[-2 -1  0  1  2  3]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


Comprobar que, salvo la multiplicación, ninguno estaba permitido en listas. ¿Qué hace la multiplicación en el caso de una lista?

## Creación de arreglos

Si bien podemos crear arreglos a partir de listas, NumPy viene con muchas funciones para hacerlo. Veamos algunas.

Una muy utilizada es `np.arange()`. Consulta su documentación. Otra opción es que, en una celda de código, escribas `np.arange` y aprietes `shift` + `tab`. De esa forma, te aparecerá la ayuda.

Juega un poco con el ejemplo a continuación.

In [ ]:
arreglo = np.arange(3,20,2)
print(arreglo)

array = np.linspace(0,100,20)
print(array)

print(np.zeros(10))

print(np.ones(6))

[ 3  5  7  9 11 13 15 17 19]
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


**Ejercicio:** investiga y crea ejemplos con las siguientes funciones
* `np.linspace`. Presta particular atención a cómo se diferencia de `np.arange`.
* `np.zeros` y `np.ones`.



## Shape de los arreglos

Los arreglos tienen muchos más propiedades que las listas. En particular, pueden tener más de un *eje* o dimensión. Veamos a qué nos referimos:

In [ ]:
arreglo_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arreglo_2d)

[[1 2 3 4]
 [5 6 7 8]]


Notar que tiene dos filas y cuatro columnas. Podemos descubrir esto sin imprimirlo en pantalla, sino usando la propiedad `.shape` del arreglo.

In [ ]:
print(arreglo_2d.shape)

(2, 4)


Primero aparece el número de filas y luego el de columnas. ¿Qué estructura de dato es `(2, 4)`? Otro ejemplo:

In [ ]:
arreglo_2d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arreglo_2d)
print(arreglo_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


Si queremos saber cuántos elementos tiene, podemos usar `.size`

In [ ]:
print(arreglo_2d.size)

8


## Accediendo elementos

Al igual que las listas, los elementos del arreglo se acceden mediante su índice, comenzando desde 0.

In [ ]:
arreglo_2d = np.arange(9).reshape(3,3)
print(arreglo_2d)
print(arreglo_2d[1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


In [ ]:
print(arreglo_2d[0])
print(arreglo_2d[0,0])
print(arreglo_2d[1,0])

[0 1 2]
0
3


Podemos seleccionar una rebanadas del arreglo de la siguiente manera:
	
	>Objeto[desde:hasta:tamaño_de_paso]

El parámetro tamaño_de_paso permite, por ejemplo, seleccionar elementos de dos en dos

Atención a estos detalles:	 
* El índice "desde" es inclusivo.
* El índice "hasta" es exclusivo.


In [ ]:
rango = range(0,10)
Np_diez_numeros = np.array(rango)
Np_diez_numeros


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Np_diez_numeros[:4]
#Np_diez_numeros[4:7]
#Np_diez_numeros[::2]
#Np_diez_numeros[::-2]

array([9, 7, 5, 3, 1])

Podemos seleccionar elementos desde atrás para adelante mediante índices negativos, comenzando desde -1

In [ ]:
print(arreglo_2d[-1])

[6 7 8]


Para arreglos **multidimensionales**, especificar los índices de manera ordenada:

	>Objeto[dimensión1, dimensión2,…]

Veamos algunos ejemplos...
* Tercera fila, todas las columnas:
* Primeras dos filas, primeras dos columnas:
* Tercera fila, cuarta columna:


In [ ]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones



array([[5, 0, 8, 2],
       [2, 8, 1, 7],
       [5, 2, 4, 6]])

In [ ]:
Np_random_dimensiones[2,:].shape


(4,)

In [ ]:
Np_random_dimensiones[:2,:2].shape

(2, 2)

In [ ]:
Np_random_dimensiones[2,3]

3

## Ejercitación

**Ejercicio 1**: Escribir un arreglo con 50 números equiespaciados del 0 al 9. Pista: `linspace`

In [ ]:
arreglo = np.linspace(0,9,50)
arreglo

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

**Ejercicio 2:** crear un arreglo 1D de 20 ceros. Reemplazar los primeros 15 elementos por unos.

In [ ]:
arreglo = np.arange(20)
arreglo[:15] = 1


array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 15, 16,
       17, 18, 19])

**Ejercicio 3:** crear un arreglo 1D de 50 ceros. Reemplazar los primeros 25 elementos por los números naturales del 0 al 24.

In [ ]:
arreglo = np.zeros(50)
arreglo[:25] = range(0,25)
arreglo

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

**Ejercicio 4:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la segunda columna por los números 1, 2 y 3 respectivamente. Es decir, crear la siguiente matriz:

```
0 1 0 
0 2 0
0 3 0
```

In [ ]:
arreglo = np.zeros(9).reshape(3,3)

arreglo[:,1] = np.arange(1,4)

arreglo



array([[0., 1., 0.],
       [0., 2., 0.],
       [0., 3., 0.]])

**Ejercicio 5:** crear un arreglo 2D de 3 filas y 3 columnas, lleno de ceros. Reemplazar los elemento de la diagonal por unos. Es decir, crear la siguiente matriz:

```
1 0 0 
0 1 0
0 0 1
```

In [ ]:
arreglo = np.zeros(9).reshape(3,3)


range(0,2,1)

arreglo

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Ejercicio 6:** Comprobar si efectivamente es más rápido utilizar `numpy` en lugar de python nativo para realizar operaciones. Probar la suma de los primeros 100.000 números naturales, y como segundo ejemplo, sumarle 5 a esos números

Utilizar la función mágica `%%timeit` al inicio del código. La misma calcula la celda varias veces y devuelve en promedio cuanto tiempo se demoró la computadora para hacer el cálculo

In [ ]:
array = np.array(range(1,100001))
acu = 0
for i in array:
  acu += i
acu

5000050000

In [ ]:
array = np.array(range(1,100001))
acu = 0
for i in array:
  acu += i + 5
acu

5000550000

## Funciones que operan sobre arreglos

Los arreglos de NumPy incorporan un montón de funciones que operan sobre los arreglos. Veamos algunos ejemplos.

In [ ]:
un_arreglo = np.array([-100,2,3,17,25,1,95])
print(un_arreglo.min())
print(un_arreglo.max())

-100
95


En el caso 2D, podemos pedir que estas funciones operen sobre todo el arreglo, o por ejes.



In [ ]:
# No te preocupes si no entiendes lo que hace esta celda
arreglo_2d = np.arange(9)
np.random.shuffle(arreglo_2d)
arreglo_2d = arreglo_2d.reshape((3,3))
print(arreglo_2d)

[[6 4 1]
 [3 0 2]
 [8 5 7]]


Trata de entender la diferencia entre las siguientes instrucciones:

In [ ]:
print(arreglo_2d.max())
print(arreglo_2d.max(axis = 0))
print(arreglo_2d.max(axis = 1))

8
[8 5 7]
[6 3 8]


### Reshape

Permite modificar la dimensión de un arreglo, retornando otro con distinta dimensión y forma pero manteniendo los mismos elementos.




In [ ]:
np.arange(1,65)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

**Error al redimensionar.**

Para que podamos cambiar el número de filas y columnas de un arreglo en Python, debemos cumplir una única condición, la cual es que las nuevas dimensiones sean compatibles con las dimensiones originales, es decir, que tengan el mismo número de elementos.

Si tenemos un arreglo de 1×8, podemos convertirlo en un arreglo de 2×4, 4×2 y 8×1.

In [ ]:
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

Sencillo, ¿verdad? 😀



### Concatenación

Consiste en formar un nuevo arreglo a partir de “enganchar” o “apilar” otros.
Python ofrece dos métodos:
* Con la operación concatenate. 
* Con las operaciones vstack y hstack 


In [ ]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
print(Arrays_concatenados.reshape(2,5))

[[1 2 9 7 9]
 [8 3 1 9 4]]


El método vstack apila verticalmente:



In [ ]:
Array_extra = np.array([[10],[20]])
Array_extra


array([[10],
       [20]])

In [ ]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

Y si es horizontal ❓

In [ ]:
Array_apilados_h = np.XX ([Array_extra, Array_extra])
Array_apilados_h

AttributeError: ignored

### Splitting

Consiste en desarmar o partir los arreglos. Puede pensarse como la operación inversa a la concatenación



In [ ]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([3, 3]), array([2, 8, 0, 6, 0, 5, 5, 2])]

Especificamos los puntos de corte con un arreglo. En este caso queremos un único corte entre el segundo y tercer elemento


In [ ]:
Array_partido_2 = np.split(Arrays_concatenados, [2, 8]) # dos puntos de corte
Array_partido_2

[array([3, 3]), array([2, 8, 0, 6, 0, 5]), array([5, 2])]

In [ ]:
Parte_1, Parte_2, Parte_3 = Array_partido_2 # Podemos desarmar el arreglo y guardarlo en variables distintas


In [ ]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [4]) # corte horizontal
Ajedrez_partido_1


[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]), array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [ ]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4]) # corte vertical
Ajedrez_partido_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

## Agregaciones y Operaciones vectorizadas

Calculo del promedio:

> Una solución tradicional al problema es la siguiente:
 
> Si bien esta correcta la respuesta numpy nos facilita el labor

In [ ]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)


[5 3 9 7 2 4 0 3 1 2]


Estas funciones están optimizadas para grandes volúmenes de datos y además nos ahorran mucho código… 😉

In [ ]:
Array_aleatorio.sum()
Array_aleatorio.mean()
Array_aleatorio.max()
Array_aleatorio.min()
Array_aleatorio.std()


2.615339366124404

In [ ]:
np.median(Array_aleatorio)
np.std(Array_aleatorio)
np.var(Array_aleatorio)

6.840000000000001

**¿Por qué son tan importantes?**

* Incluso las operaciones más sencillas pueden resultar muy lentas si las llevamos a cabo elemento a elemento.
* Las computadoras son especialmente buenas para realizar cálculos en paralelo 🖥️
* Las operaciones vectorizadas o funciones universales (ufuncs) nos permiten operar entre arreglos de la manera más rápida posible

## Numpy para generar números aleatorios

De los múchos métodos y funcionalidades que tiene Numpy, encontramos la posibilidad de generar números aleatorios para poder probar con información "inventada"

Si bien la documentación es amplia, podemos utilizar solo una parte para generar conjuntos de datos

Lo mas simple es generar un número aleatorio (similar a la función del Excel)

In [ ]:
np.random.random()

0.36976654547837673

Podemos notar que cada vez que ejecutamos la celda nos devuelve un número diferente. Para ello, podemos definir una semilla, es decir un valor para que cada vez que generemos un número "aleatorio", este sea el mismo

In [ ]:
np.random.seed(200)
np.random.random()

0.9476322568516703

In [ ]:
np.random.random()

0.226547421131723

Podemos generar un arreglo de varios números

`random.randint(low, high=None, size=None, dtype=int)`

In [ ]:
#low = desde
#high = hasta
#size = cantidad de números
np.random.randint(low=1,high=50,size=15)

array([43, 13, 16, 26, 15, 28, 26, 12,  7, 43,  2,  8, 28, 10, 16])

En ciertas oportunidades va a resultar conveniente generar números aleatorios con alguna `distribución` asociada. Vamos a verlo más adelante, pero podemos utilizar algunas de las más conocidas

*Distribución Normal*

`random.normal(loc=0.0, scale=1.0, size=None)`

In [ ]:
#loc = podemos entenderlo como el promedio
#scale = podemos entenderlo como el desvío estandar
#size = tamaño del array
np.random.normal(loc=50,scale=5,size=100)

array([55.99867262, 44.9496031 , 45.26248116, 51.36728008, 47.29137931,
       47.08067669, 50.85082864, 40.38365567, 51.54718915, 49.58745591,
       52.8630366 , 53.59204405, 50.49626641, 46.74974068, 52.94623975,
       49.89433   , 52.35554913, 55.57491899, 53.79381499, 48.36454988,
       55.27898018, 51.89445259, 46.56311576, 45.0292235 , 50.81166377,
       45.56422612, 42.65552426, 50.05878111, 39.41368075, 50.1321104 ,
       49.21515213, 41.32177506, 53.56269174, 41.90348108, 41.2477114 ,
       50.80916755, 42.48530111, 55.66842071, 48.51060178, 46.9906809 ,
       46.70833376, 41.53231662, 42.60545074, 53.65326155, 46.30626468,
       54.98186291, 51.72073449, 53.25273551, 43.01562595, 46.31950902,
       51.88419212, 48.21474515, 58.73488556, 45.32160044, 51.20943035,
       42.37034359, 54.4983738 , 45.01831362, 55.52942486, 49.24421545,
       46.02041706, 47.63579591, 52.06878785, 41.06502333, 49.05618729,
       57.55664513, 56.93915937, 52.15657706, 54.19871243, 47.39

## Ejercitación EXTRA

**Ejercicio 7**: Calcular la suma de los primeros 1000 números pares

**Ejercicio 8**: A partir de una distribución Normal con loc = 100 y scale = 30 generar:

1 array de 50 números

1 array de 500 números

1 array de 1000 números

1 array de 10.000 números

Para cada uno de ellos, calcular el promedio y el desvío. Algo que llame la atención?